// Dados de exemplo do quadro
window.BOARD_DATA = {
  filters: ['Todos', 'Bordado', 'DTF', 'Sem personalização', 'Serigrafia', 'Serigrafia e Bordado', 'Sublimação'],
  procColors: {
    'Bordado':              '#9a88b8',
    'DTF':                  '#13c2c2',
    'Sem Personalização':   '#8592a6',
    'Serigrafia':           '#1677ff',
    'Serigrafia e Bordado': '#722ed1',
    'Sublimação':           '#52c41a',
  },
  columns: [
    {
      id: 'preparando',
      title: 'Preparando Arte',
      color: 'var(--col-1)',
      cards: [
        { id: 1,  client: 'Tomaz Potiguar',        process: 'Sublimação', status: 'Tudo OK', due: '05/06/26', dot: 'green', fabric: 'Malha PV',     qty: 84 },
        { id: 2,  client: 'SESI Rio Grande do Sul', process: 'DTF',        status: 'Tudo OK', due: '27/06/26', dot: 'green', fabric: 'Algodão',      qty: 150 },
        { id: 3,  client: 'SESI Rio Grande do Sul', process: 'Sublimação', status: 'Tudo OK', due: '22/06/26', dot: 'green', fabric: 'Dry-fit',      qty: 220 },
        { id: 4,  client: 'SESI Rio Grande do Sul', process: 'Sublimação', status: 'Tudo OK', due: '27/06/26', dot: 'green', fabric: 'Dry-fit',      qty: 180 },
        { id: 5,  client: 'SESI Rio Grande do Sul', process: 'DTF',        status: 'Tudo OK', due: '27/06/26', dot: 'green', fabric: 'Algodão',      qty: 96 },
        { id: 6,  client: 'SESI Rio Grande do Sul', process: 'DTF',        status: 'Tudo OK', due: '27/06/26', dot: 'green', fabric: 'Algodão',      qty: 120 },
        { id: 7,  client: 'SESI Rio Grande do Sul', process: 'Sublimação', status: 'Tudo OK', due: '29/06/26', dot: 'green', fabric: 'Dry-fit',      qty: 64 },
        { id: 8,  client: 'Confecções Aurora',      process: 'Bordado',    status: 'Tudo OK', due: '08/06/26', dot: 'green', fabric: 'Sarja',        qty: 40 },
      ],
    },
    {
      id: 'exportado',
      title: 'Exportado/Arte Separada',
      color: 'var(--col-2)',
      cards: [
        { id: 11, client: 'MJ Feo',           process: 'Bordado',    status: 'Tudo OK', due: '30/05/26', dot: 'amber', fabric: 'Brim',     qty: 24 },
        { id: 12, client: 'Bruno de Oliveira', process: 'Bordado',    status: 'Tudo OK', due: '25/05/26', dot: 'amber', fabric: 'Piquet',   qty: 18 },
        { id: 13, client: 'Eldorado Madeiras', process: 'Sublimação', status: 'Tudo OK', due: '11/06/26', dot: 'green', fabric: 'Dry-fit',  qty: 60 },
        { id: 14, client: 'Ademir Malharia',   process: 'Sublimação', status: 'Tudo OK', due: '04/06/26', dot: 'green', fabric: 'PV',       qty: 42 },
        { id: 15, client: 'Daniel Vitorino',   process: 'Bordado',    status: 'Tudo OK', due: '05/06/26', dot: 'green', fabric: 'Sarja',    qty: 12 },
        { id: 16, client: 'Tomaz Potiguar',    process: 'Sublimação', status: 'Tudo OK', due: '05/06/26', dot: 'green', fabric: 'Dry-fit',  qty: 36 },
        { id: 17, client: 'Adriana Aparecida', process: 'Sublimação', status: 'Tudo OK', due: '12/06/26', dot: 'green', fabric: 'Dry-fit',  qty: 48 },
      ],
    },
    {
      id: 'imprimindo',
      title: 'Imprimindo/Fotolito Impresso',
      color: 'var(--col-3)',
      cards: [
        { id: 21, client: 'Maria Eduarda',           process: 'Sublimação', status: 'Tudo OK', due: '16/06/26', dot: 'green', fabric: 'Dry-fit', qty: 30 },
        { id: 22, client: 'Priscila Confecções e Cia', process: 'Sublimação', status: 'Tudo OK', due: '15/05/26', dot: 'red',   fabric: 'PV',      qty: 75 },
      ],
    },
    {
      id: 'impresso',
      title: 'Impresso/Na Estamparia',
      color: 'var(--col-4)',
      cards: [
        { id: 31, client: 'Pé Legal',                  process: 'Serigrafia', status: 'Tudo OK', due: '30/04/26', dot: 'red',   fabric: 'Algodão',  qty: 200 },
        { id: 32, client: 'Pé Legal',                  process: 'Serigrafia', status: 'Tudo OK', due: '30/04/26', dot: 'red',   fabric: 'Algodão',  qty: 144 },
        { id: 33, client: 'Transporte Escolar da Cida', process: 'Serigrafia', status: 'Tudo OK', due: '19/05/26', dot: 'red',   fabric: 'Algodão',  qty: 22 },
        { id: 34, client: 'Jean Correa',                process: 'Serigrafia', status: 'Tudo OK', due: '20/05/26', dot: 'red',   fabric: 'Piquet',   qty: 16 },
        { id: 35, client: 'SENAI Aparecida do Taboado', process: 'Serigrafia', status: 'Tudo OK', due: '22/05/26', dot: 'red',   fabric: 'Algodão',  qty: 88 },
        { id: 36, client: 'Larissa Cordeiro',           process: 'Serigrafia', status: 'Tudo OK', due: '22/05/26', dot: 'red',   fabric: 'Algodão',  qty: 12 },
        { id: 37, client: 'Supermercado Thiago',        process: 'Sublimação', status: 'Tudo OK', due: '26/05/26', dot: 'amber', fabric: 'Dry-fit',  qty: 56 },
      ],
    },
    {
      id: 'sublimado',
      title: 'Sublimado/Estampado',
      color: 'var(--col-5)',
      cards: [
        { id: 41, client: 'SESI Palmas',          process: 'Sem Personalização', status: 'Tudo OK', due: '22/05/26', dot: 'green', fabric: 'Dry-fit',  qty: 320 },
        { id: 42, client: 'Supermercado Thiago',  process: 'Sublimação',         status: 'Tudo OK', due: '28/05/26', dot: 'green', fabric: 'PV',       qty: 60 },
        { id: 43, client: 'Pé Legal',             process: 'Bordado',            status: 'Tudo OK', due: '30/04/26', dot: 'green', fabric: 'Brim',     qty: 24 },
        { id: 44, client: 'Senai esc. construção', process: 'Serigrafia',         status: 'Tudo OK', due: '30/04/26', dot: 'green', fabric: 'Algodão',  qty: 110 },
        { id: 45, client: 'Gustavo Baldo',         process: 'Serigrafia',         status: 'Tudo OK', due: '30/04/26', dot: 'green', fabric: 'Algodão',  qty: 18 },
        { id: 46, client: 'Pé Legal',              process: 'Bordado',            status: 'Tudo OK', due: '30/04/26', dot: 'green', fabric: 'Sarja',    qty: 36 },
        { id: 47, client: 'Wanderson de Oliveira', process: 'Sublimação',         status: 'Tudo OK', due: '02/05/26', dot: 'green', fabric: 'Dry-fit',  qty: 24 },
      ],
    },
  ],
};
